export type ShapeCell = {
  row: number;
  col: number;
};

export type ShapeDefinition = {
  id: string;
  name: string;
  color: string;
  accentLabel: string;
  accentPattern: "coin" | "bill" | "vault" | "card" | "chart" | "bank";
  cells: ShapeCell[];
};

export const SHAPES: ShapeDefinition[] = [
  {
    id: "single",
    name: "Single",
    color: "bg-emerald-400",
    accentLabel: "APR",
    accentPattern: "coin",
    cells: [{ row: 0, col: 0 }],
  },
  {
    id: "line-2-h",
    name: "Line 2 H",
    color: "bg-cyan-400",
    accentLabel: "FX",
    accentPattern: "chart",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
    ],
  },
  {
    id: "line-2-v",
    name: "Line 2 V",
    color: "bg-sky-400",
    accentLabel: "PAY",
    accentPattern: "card",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
    ],
  },
  {
    id: "line-3-h",
    name: "Line 3 H",
    color: "bg-blue-400",
    accentLabel: "POS",
    accentPattern: "card",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
    ],
  },
  {
    id: "line-3-v",
    name: "Line 3 V",
    color: "bg-indigo-400",
    accentLabel: "ATM",
    accentPattern: "bank",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
    ],
  },
  {
    id: "line-4-h",
    name: "Line 4 H",
    color: "bg-violet-400",
    accentLabel: "BANK",
    accentPattern: "bank",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
    ],
  },
  {
    id: "line-4-v",
    name: "Line 4 V",
    color: "bg-purple-400",
    accentLabel: "SAFE",
    accentPattern: "vault",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
      { row: 3, col: 0 },
    ],
  },
  {
    id: "line-5-h",
    name: "Line 5 H",
    color: "bg-fuchsia-400",
    accentLabel: "FLOW",
    accentPattern: "chart",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
    ],
  },
  {
    id: "line-5-v",
    name: "Line 5 V",
    color: "bg-pink-400",
    accentLabel: "VAULT",
    accentPattern: "vault",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
      { row: 3, col: 0 },
      { row: 4, col: 0 },
    ],
  },
  {
    id: "square-2",
    name: "Square",
    color: "bg-amber-400",
    accentLabel: "USD",
    accentPattern: "bill",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
    ],
  },
  {
    id: "rect-3x2",
    name: "Card 3x2",
    color: "bg-yellow-400",
    accentLabel: "CARD",
    accentPattern: "card",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
    ],
  },
  {
    id: "rect-2x3",
    name: "Vault 2x3",
    color: "bg-lime-400",
    accentLabel: "SAFE",
    accentPattern: "vault",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
    ],
  },
  {
    id: "l-3",
    name: "L 3",
    color: "bg-orange-400",
    accentLabel: "ROI",
    accentPattern: "chart",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
    ],
  },
  {
    id: "l-3-mirror",
    name: "L 3 Mirror",
    color: "bg-red-400",
    accentLabel: "TAX",
    accentPattern: "bill",
    cells: [
      { row: 0, col: 1 },
      { row: 1, col: 1 },
      { row: 1, col: 0 },
    ],
  },
  {
    id: "corner-3-top",
    name: "Corner 3 Top",
    color: "bg-rose-400",
    accentLabel: "PIN",
    accentPattern: "card",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 0 },
    ],
  },
  {
    id: "corner-3-top-mirror",
    name: "Corner 3 Mirror",
    color: "bg-teal-400",
    accentLabel: "NFC",
    accentPattern: "card",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 1 },
    ],
  },
  {
    id: "l-4",
    name: "L 4",
    color: "bg-emerald-500",
    accentLabel: "LOAN",
    accentPattern: "bill",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
    ],
  },
  {
    id: "j-4",
    name: "J 4",
    color: "bg-cyan-500",
    accentLabel: "CARD",
    accentPattern: "card",
    cells: [
      { row: 0, col: 1 },
      { row: 1, col: 1 },
      { row: 2, col: 1 },
      { row: 2, col: 0 },
    ],
  },
  {
    id: "l-4-top",
    name: "L 4 Top",
    color: "bg-sky-500",
    accentLabel: "BILL",
    accentPattern: "bill",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
    ],
  },
  {
    id: "j-4-top",
    name: "J 4 Top",
    color: "bg-indigo-500",
    accentLabel: "IBAN",
    accentPattern: "bank",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 1 },
      { row: 2, col: 1 },
    ],
  },
  {
    id: "t-4-down",
    name: "T Down",
    color: "bg-violet-500",
    accentLabel: "COIN",
    accentPattern: "coin",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 1, col: 1 },
    ],
  },
  {
    id: "t-4-up",
    name: "T Up",
    color: "bg-purple-500",
    accentLabel: "MOBY",
    accentPattern: "bank",
    cells: [
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
    ],
  },
  {
    id: "t-4-left",
    name: "T Left",
    color: "bg-fuchsia-500",
    accentLabel: "CHIP",
    accentPattern: "card",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
      { row: 1, col: 1 },
    ],
  },
  {
    id: "t-4-right",
    name: "T Right",
    color: "bg-pink-500",
    accentLabel: "QR",
    accentPattern: "chart",
    cells: [
      { row: 0, col: 1 },
      { row: 1, col: 1 },
      { row: 2, col: 1 },
      { row: 1, col: 0 },
    ],
  },
  {
    id: "zig-4",
    name: "Zig",
    color: "bg-lime-500",
    accentLabel: "LEDG",
    accentPattern: "bank",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
    ],
  },
  {
    id: "step-4",
    name: "Step",
    color: "bg-teal-500",
    accentLabel: "CASH",
    accentPattern: "vault",
    cells: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
    ],
  },
  {
    id: "plus-5",
    name: "Plus",
    color: "bg-green-400",
    accentLabel: "PLUS",
    accentPattern: "coin",
    cells: [
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 2, col: 1 },
    ],
  },
  {
    id: "u-5",
    name: "U Vault",
    color: "bg-blue-500",
    accentLabel: "SAFE",
    accentPattern: "vault",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 2 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
    ],
  },
  {
    id: "p-5",
    name: "P Block",
    color: "bg-amber-500",
    accentLabel: "BANK",
    accentPattern: "bank",
    cells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 2, col: 0 },
    ],
  },
  {
    id: "corner-5",
    name: "Big Corner",
    color: "bg-orange-500",
    accentLabel: "FUND",
    accentPattern: "chart",
    cells: [
      { row: 0, col: 0 },
      { row: 1, col: 0 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
    ],
  },
];
